### ISSUE TITLE
[Rule Suggestion] Update/Rewrite Rule 3.1 (Suggestion to outlaw in-claim griefs)

### ISSUE THREAD

**Issue by SuperChrisBoy** [EarthMC/EarthMC.net#100] opened 2020-03-11 02:07 UTC
I've seen a lot of tickets regarding griefing in claims and players complaining about why the griefers are not warned for that offense. Griefing anywhere in a town, in my opinion, should count as a warnable offense. I just came to a case today that a mayor got severely griefed by his/her only town members. Unfortunately, the current rule says that "mayors/kings are responsible for misconfigured town/nation permission settings" which sounded like the victim (mayor) should take the total blame, but not the actual griefer. I think in-claim grief should be equally treated as proximity grief. So I'm here to suggest to add/rewrite rule 3.1 to outlaw in-claim griefing.

**Comment by ghost** [comment] 2020-03-11 02:11
i agree with this proposal, i hate being the bearer of bad news to mayors who make honest mistakes when it comes to town/nation permissions. They shouldn't be help fully responsible for what griefers do imo.

**Comment by Rezolent** [comment] 2020-03-11 02:22
Agreed. Unless it is within a hollowclaim. You know what to expect when you make a hollow claim and don't fill it in.

**Comment by AmphireYT** [comment] 2020-03-11 02:36
well what if like the player i guess griefs his own town (this is a scenario) because he hates the mayor. or vice versa who you gonna give the warns too

**Comment by AmphireYT** [comment] 2020-03-11 02:36
its kinda the mayors fault for picking that person but otherwise I agree To this

**Comment by ghost** [comment] 2020-03-11 02:41
how should a mayor know how a players acts if they just joined the server, its one thing if the player is semi known to be troll, but for newer players, its impossible to tell.

**Comment by SuperChrisBoy** [comment] 2020-03-11 02:42
> well what if like the player i guess griefs his own town (this is a scenario) because he hates the mayor. or vice versa who you gonna give the warns too

It would be counted as griefing thus should be warned. Wouldn't that be the same reason for players to proximity grief? There is no need for the mayor to grief the town member because the mayor can just simply kick the player out of the town.

**Comment by AmphireYT** [comment] 2020-03-11 02:43
> how should a mayor know how a players acts if they just joined the server, its one thing if the player is semi known to be troll, but for newer players, its impossible to tell.

true but Mayers should pay close attention to them when they invite a new member

**Comment by AmphireYT** [comment] 2020-03-11 02:45
> > well what if like the player i guess griefs his own town (this is a scenario) because he hates the mayor. or vice versa who you gonna give the warns too
> 
> It would be counted as griefing thus should be warned. Wouldn't that be the same reason for players to proximity grief? There is no need for the mayor to grief the town member because the mayor can just simply kick the player out of the town.

well what if they needed a reason too, cuz the rest of the members doesnt want "the person" kicked

**Comment by SnUncle** [comment] 2020-03-11 02:48
Sounds sweet. But feeling like staff member would have to pay more attention on townmember grief cases if the rule been updated like this.

**Comment by AmphireYT** [comment] 2020-03-11 02:50
> Sounds sweet

bruh

**Comment by maxifunseeker** [comment] 2020-03-11 03:23
Yeah, I totally agree with this.

**Comment by ghost** [comment] 2020-03-11 12:09
I agree with this. A rival nation found one chunk with incorrect perms in the water on the coast. They opened a pit down to bedrock and filled it with lava. No one was warned. They're wasting mod time and getting a free pass on it. If the area was unclaimed they would have gotten a warning which is bizarre. Towny commands are confusing and especially so for inexperienced players. Griefing is griefing. In town or near town you should get a warning.

**Comment by shirazmatas** [comment] 2020-03-11 16:30
duplicate of #32

**Closed as completed** 2020-04-12 14:53 UTC
Labels: Rules
