### ISSUE TITLE
Protect ice roads in the same way as railroads

### ISSUE THREAD

**Issue by tribubb** [EarthMC/EarthMC.net#14] opened 2019-01-18 01:49 UTC
Railroads are protected by anti-grief rules though roads of the ice, packed ice and blue ice variety are not explicitly protected by these same rules despite being the main connection between some cities on the server. Could ice roads be provided the protection of these anti-grief rules?

**Comment by shirazmatas** [comment] 2019-03-21 16:33
This is a duplicate of #10

**Comment by KarlOfDuty** [comment] 2019-04-07 14:51
Indeed.

**Closed as completed by KarlOfDuty** 2019-04-07 14:51 UTC
